singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s591 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s592 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s593 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s594 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s595 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s596 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s597 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s598 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s601 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s602 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s603 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s604 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s605 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s606 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s607 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s608 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s609 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s610 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s611 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s612 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s614 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s615 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s616 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s617 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s618 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s619 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s621 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s622 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s623 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s624 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s625 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s626 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s627 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s628 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s629 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s631 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s633 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s634 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s635 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s636 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s638 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s639 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s640 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s641 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s642 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s643 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s644 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s645 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s646 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s647 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s648 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s649 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s650 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s061 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s491 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s495 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s513 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s525 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s526 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s541 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s546 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s548 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s549 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s553 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s554 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s555 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s556 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s557 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s558 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s561 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s567 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s568 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s570 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s572 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s573 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s574 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s577 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s579 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s581 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s582 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s583 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s584 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s585 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s586 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s587 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s588 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s589 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s590 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s061 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s491 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s495 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s513 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s525 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s526 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s541 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s546 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s548 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s549 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s553 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s554 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s555 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s556 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s557 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s558 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s561 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s567 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s568 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s570 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s572 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s573 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s574 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s577 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s579 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s581 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s582 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s583 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s584 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s585 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s586 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s587 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s588 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s589 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s590 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s591 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s592 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s593 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s594 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s595 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s596 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s597 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s598 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s601 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s602 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s603 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s604 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s605 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s606 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s607 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s608 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s609 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s610 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s611 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s612 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s614 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s615 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s616 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s617 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s618 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s619 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s621 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s622 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s623 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s624 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s625 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s626 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s627 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s628 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s629 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s631 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s633 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s634 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s635 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s636 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s637 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s638 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s639 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s640 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s641 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s642 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s643 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s644 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s645 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s646 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s647 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s648 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s649 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s650 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s061 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s491 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s495 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s513 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s525 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s526 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s541 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s546 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s548 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s549 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s553 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s554 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s555 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s556 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s557 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s558 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s561 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s567 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s568 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s570 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s572 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s573 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s574 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s577 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s579 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s581 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s582 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s583 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s584 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s585 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s586 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s587 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s588 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s589 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/users/ieisenbe/Self_Regulation_Ontology/fmri_analysis/fmriprep participant --participant_label s590 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
