singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s513 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s579 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s597 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s598 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s601 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s602 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s603 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s604 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s605 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s606 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s607 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s608 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s609 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s614 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s615 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s617 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s619 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s623 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s625 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s518 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s593 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s616 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s618 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s621 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s622 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s624 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s626 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s627 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s628 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s629 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s631 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s633 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s634 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s635 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s636 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s638 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s639 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s640 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s641 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s642 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s643 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s644 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s645 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s646 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s647 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s648 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s649 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
singularity run /share/PI/russpold/singularity_images/poldracklab_fmriprep_1.0.8-2018-02-23-8c60ec5604ac.img /oak/stanford/groups/russpold/data/uh2/BIDS_data /oak/stanford/groups/russpold/data/uh2/BIDS_data/derivatives/fmriprep participant --participant_label s650 -w /scratch/users/ieisenbe --fs-license-file /home/users/ieisenbe/docs/fs-license.txt --output-space template T1w --mem_mb 40000 --nthreads 10 --anat-only
